### ISSUE TITLE
build failure - Failed to execute goal org.apache.maven.plugins...

### ISSUE THREAD

**Issue by tweinreich** [codescape/maven-geb-and-spock-tests#3]
First here my specs:
**OS:** OS X 10.9.5
**JVM:** 1.8.0_45
**Groovy:** 2.4.4
**Maven:** 3.3.9

And here is my terminal output, does somebody know how to fix this?

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 9.839 s
> [INFO] Finished at: 2016-05-04T22:41:15+02:00
> [INFO] Final Memory: 16M/201M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.8.1:test (default-test) on project maven-geb-and-spock-tests: There are test failures.
> [ERROR]
> [ERROR] Please refer to /Users/UserName/web_projects/maven-geb-and-spock-tests/target/surefire-reports for the individual test results.
> [ERROR] -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.8.1:test (default-test) on project maven-geb-and-spock-tests: There are test failures.
> 
> Please refer to /Users/UserName/web_projects/maven-geb-and-spock-tests/target/surefire-reports for the individual test results.
>   at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
>   at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
>   at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
>   at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
>   at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
>   at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
>   at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
>   at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
>   at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
>   at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
>   at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
>   at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
>   at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:497)
>   at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
>   at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
>   at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
>   at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.
> 
> Please refer to /Users/UserName/web_projects/maven-geb-and-spock-tests/target/surefire-reports for the individual test results.
>   at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:74)
>   at org.apache.maven.plugin.surefire.SurefirePlugin.writeSummary(SurefirePlugin.java:644)
>   at org.apache.maven.plugin.surefire.SurefirePlugin.executeAfterPreconditionsChecked(SurefirePlugin.java:640)
>   at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:102)
>   at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
>   at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
>   ... 20 more
> [ERROR]
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by tweinreich** [comment]
I didn't resolve the issue exactly but I ignored it, did a _mvn idea:idea_ and got the demo imported into IntelliJ Idea. The tests run as expected here.
